/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisTimeline: typeof import('./../components/app/AnalysisTimeline.vue')['default']
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    HelpDialog: typeof import('./../components/app/HelpDialog.vue')['default']
    RenderData: typeof import('./../components/app/RenderData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/app/SearchForm.vue')['default']
  }
}
